name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Dependencies
      run: bun install

    - name: Run Games Unit Tests
      working-directory: ./services/games
      run: bun test tests/unit

    - name: Run Wallets Unit Tests
      working-directory: ./services/wallets
      run: bun test tests/unit

    - name: Run Games E2E Tests
      working-directory: ./services/games
      run: bun test tests/e2e
